version: '3.7'

volumes:
  Reference_Keycloak_Quayio_Db:
      driver: local

services:
  keycloak:
    container_name: ${KEYCLOAK_SERVER_CONTAINER_NAME}
    image: quay.io/keycloak/keycloak:legacy
    restart: always
    depends_on:
      - postgres
    ports:
      - ${KEYCLOAK_SERVER_PORT}:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${KEYCLOAK_POSTGRES_DATABASE}
      DB_SCHEMA: public
      DB_USER: ${KEYCLOAK_POSTGRES_USER}
      DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_SERVER_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_SERVER_PASSWORD}
    command:
      -Dkeycloak.profile.feature.upload_scripts=enabled

  postgres:
    container_name: ${KEYCLOAK_POSTGRES_CONTAINER_NAME}
    image: postgres:15.3
    restart: always
    volumes:
      - Reference_Keycloak_Quayio_Db:/var/lib/postgresql/data
    ports:
      - ${KEYCLOAK_POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DATABASE}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
