version: '3.7'

services:
  template:
    container_name: ${TEMPLATE_CONTAINER_NAME}
    image: template
    restart: always
    volumes:
      - ./data:/app
    ports:
      - ${TEMPLATE_PORT}:8080
    environment:
      - TEMPLATE_ENV=${TEMPLATE_ENV}
