version: '3.7'

services:
  loki:
    container_name: ${LOKI_LOKI_CONTAINER_NAME}
    image: grafana/loki:2.8.2  # latest release can be found in https://github.com/grafana/loki/releases
    restart: always
    volumes:
      - ${LOKI_CONFIG_PATH}loki/config.yml:/etc/loki/config.yml
      - ${LOKI_DATA_PATH}:/loki
    ports:
      - ${LOKI_PORT}:3100

  promtail:
    container_name: ${LOKI_PROMTAIL_CONTAINER_NAME}
    image: grafana/promtail:2.8.2
    restart: always
    volumes:
      - ${LOKI_CONFIG_PATH}promtail/config.yml:/etc/promtail/config.yml
      - ${LOKI_LOG_PATH}:/var/log
    command: -config.file=/etc/promtail/config.yml

  flog:
    container_name: ${LOKI_FLOG_CONTAINER_NAME}
    image: mingrammer/flog
    restart: always
    volumes:
      - ${LOKI_LOG_PATH}:/output
    command: -f apache_common -t log -d 1s -l -o /output/apache_common.log -w
