version: '3.7'

volumes:
  Reference_Metabase_Db:
    driver: local

services:
  metabase:
    image: metabase/metabase:v0.46.7
    container_name: ${METABASE_CONTAINER_NAME}
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_HOST: metabase-db
      MB_DB_PORT: '5432'
      MB_DB_USER: ${DB_USER}
      MB_DB_PASS: ${DB_PASSWORD}
    ports:
      - ${METABASE_PORT}:3000
    depends_on:
      - metabase-db

  metabase-db:
    image: postgres:15.3
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: metabase
    ports:
      - ${DB_PORT}:5432
    volumes:
      - Reference_Metabase_Db:/var/lib/mysql
