version: '3.7'

services:
  registry:
    container_name: Reference-DockerRegistry
    image: registry
    ports:
      - ${REGISTRY_PORT}:5000
    volumes:
      - ./data:/var/lib/registry
      - ./config/config.yml:/etc/docker/registry/config.yml

  registry-ui:
    container_name: Reference-DockerRegistry-Ui
    image: joxit/docker-registry-ui
    ports:
      - ${UI_PORT}:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=http://localhost:${REGISTRY_PORT}
      - SINGLE_REGISTRY=true
    depends_on:
      - registry