version: '3.7'

volumes:
  Reference_Keycloak_Db:
      driver: local

services:
  postgres:
    container_name: Reference-Keycloak-Postgres
    image: postgres:15.3
    restart: always
    volumes:
      - Reference_Keycloak_Db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  keycloak:
      container_name: Reference-Keycloak-Server
      image: quay.io/keycloak/keycloak:legacy
      restart: always
      depends_on:
        - postgres
      ports:
        - ${KEYCLOAK_PORT}:8080
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: ${POSTGRES_DATABASE}
        DB_SCHEMA: public
        DB_USER: ${POSTGRES_USER}
        DB_PASSWORD: ${POSTGRES_PASSWORD}
        KEYCLOAK_USER: ${KEYCLOAK_USER}
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      command:
        -Dkeycloak.profile.feature.upload_scripts=enabled
