version: '3.7'

volumes:
  Reference_Redis_Data:
    driver: local

services:
  cache:
    container_name: ${REDIS_CACHE_CONTAINER_NAME}
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_CACHE_PORT}:6379
    volumes:
      - Reference_Redis_Data:/data
    command: redis-server --requirepass ${PASSWORD}

  admin:
    container_name: ${REDIS_ADMIN_CONTAINER_NAME}
    image: patrikx3/p3x-redis-ui:latest
    restart: always
    ports:
      - ${REDIS_UI_PORT}:7843
    volumes:
      - Reference_Redis_Data:/settings
