version: '3.7'

volumes:
  Reference_Grafana:

services:
  grafana:
    container_name: ${GRAFANA_CONTAINER_NAME}
    image: grafana/grafana:9.5.2
    restart: always
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ${GRAFANA_DATA_PATH}:/etc/grafana/provisioning/datasources
      - Reference_Grafana:/var/lib/grafana
