version: '3.7'

services:
  flog:
    container_name: ${FLOG_CONTAINER_NAME}
    image: mingrammer/flog
    restart: always
    volumes:
      - ${FLOG_LOG_PATH}/data/log:/output
    command: -f ${FLOG_LOG_FORMAT} -t log -d 1s -l -o /output/${FLOG_LOG_FORMAT}.log -w
