version: '3.7'

services:
  superset:
    container_name: ${SUPERSET_CONTAINER_NAME}
    image: apache/superset
    restart: always
    ports:
      - ${SUPERSET_PORT}:8088
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
