auth_enabled: false

server:
  http_listen_port: 3100

schema_config:
  configs:
    - from: 2023-05-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
