version: '3.7'

services:
  nginx:
    container_name: Reference-Nginx-Http
    image: nginx
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:8080

  test-server-1:
    container_name: Reference-Nginx-Test-Server-1
    image: strm/helloworld-http

  test-server-2:
    container_name: Reference-Nginx-Test-Server-2
    image: strm/helloworld-http
