server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/}
  forward-headers-strategy: framework

application:
  network:
    executorServiceUrl: ${EXECUTOR_SERVICE_URL:http://localhost:8081}
