FROM maven:3-amazoncorretto-17

WORKDIR /build

COPY pom.xml .
COPY common/pom.xml common/pom.xml
COPY executor/pom.xml executor/pom.xml
COPY gateway/pom.xml gateway/pom.xml

RUN --mount=type=cache,target=/root/.m2 mvn dependency:go-offline
